# System Configuration
detection:
  haar_cascade_path: "haarcascade_frontalface_default.xml"

preprocessing:
  clahe_clip_limit: 2.0
  clahe_tile_grid_size: [8, 8]
  bilateral_sigma_d: 5
  bilateral_sigma_r: 0.1
  min_sharpness_variance: 30

training:
  lbph_radius: 2
  lbph_neighbors: 8
  lbph_grid_x: 8
  lbph_grid_y: 8
  cross_validation_folds: 5
  learning_rate: 0.01

recognition:
  confidence_threshold_k: 1.5
  temporal_smoothing_alpha: 0.7
  min_fps: 20
  webcam_id: 0

paths:
  data_dir: "data"
  models_dir: "models"
  logs_dir: "logs"

logging:
  level: "INFO"
  file: "logs/app.log"